name: exercise_flutter_acs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-122.0.dev <4.0.0'

dependencies:
  # Para formatear fechas
  intl: ^0.20.2

  # VersiÃ³n corregida de GitHub para el selector de dÃ­as
  weekday_selector:
    git:
      url: https://github.com/smaho-engineering/weekday_selector.git
      ref: e9c604a8cabb04ea3a169c3379c270c59810e4b0

  # AÃ‘ADIDO: Necesario para seleccionar archivos del PC
  file_picker: ^6.1.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Carpetas de imÃ¡genes
  assets:
    - faces/